baseurl = "/"
languageCode = "en-us"
theme = "hello-friend"
paginate = 5

[params]
  # dir name of your blog content (default is `content/posts`)
  contentTypeName = "post"
  # "light" or "dark"
  defaultTheme = "dark"
  # if you set this to 0, only submenu trigger will be visible
  showMenuItems = 2
  # Enable to show reading time in minutes for posts
  showReadingTime = false

[languages]
  [languages.en]
    title = "Блог о питоне"
    subtitle = "A simple theme for Hugo"
    keywords = ""
    copyright = ""
    menuMore = "Показать больше"
    writtenBy = "Создан"
    readMore = "Прочитать "
    readOtherPosts = "Прочитать другие посты "
    newerPosts = "Свежие посты"
    olderPosts = "Старые посты"
    minuteReadingTime = "min read"
    dateFormatSingle = "2006-01-02"
    dateFormatList = "2006-01-02"

    [languages.en.params.logo]
      logoText = "хочу все"
      logoHomeLink = "/"
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "about"
        name = "Обо мне"
        url = "/about"
      [[languages.en.menu.main]]
        identifier = "showcase"
        name = "проекты"
        url = "/showcase"
[[languages.en.menu.main]]
        identifier = "archive"
        name = "архив"
        url = "/archive"
